---
- name: Hello World Rulebook
  hosts: localhost
  sources:
    - timer:
        interval: 60
  rules:
    - name: Run Hello World if rogthoma-dev-01 is reachable
      condition: event is defined
      action:
        run_job_template:
          name: Demo Job Template