---
- name: Hello World Rulebook
  hosts: localhost
  sources:
    - name: range
      ansible.eda.range:
        limit: 5
  rules:
    - name: Run Hello World if rogthoma-dev-01 is reachable
      condition: always
      action:
        run_job_template:
          name: Demo Job Template