---
- name: Minimal trigger
  hosts: localhost
  sources:
    - ansible.eda.webhook:
      host: 0.0.0.0
      port: 5000
  rules:
    - name: Run demo template
      action:
        run_job_template:
          name: Demo Job Template