---
- name: Minimal trigger
  hosts: localhost
  sources:
    - name: generic
      ansible.eda.generic:
        payload:
          trigger: "go"
  rules:
    - name: Run demo template
      action:
        run_job_template:
          name: Demo Job Template