---
- name: Trigger job manually with reachability check
  hosts: localhost
  sources:
    - name: generic
      ansible.eda.generic:
        payload:
          trigger: "start"

  filters:
    - name: delay_and_reachability
      type: python
      source: |
        def main(event):
            import time
            import socket
            time.sleep(60)  # Delay inside the filter
            try:
                socket.create_connection(("rogthoma-dev-01", 8000), timeout=3)
                return event
            except:
                return None

  rules:
    - name: Run Hello World if rogthoma-dev-01 is reachable
      condition: event is defined
      action:
        run_job_template:
          name: Demo Job Template