---
- name: Check reachability of rogthoma-dev-01 and run job
  hosts: localhost
  sources:
    - name: periodic
      ansible.eda.time:
        delay: 60  # every 60 seconds

  filters:
    - name: check_reachability
      type: python
      source: |
        def main(event):
            import socket
            try:
                socket.create_connection(("rogthoma-dev-01", 8000), timeout=3)
                return event  # proceed if reachable
            except:
                return None   # drop event if unreachable

  rules:
    - name: Run Hello World if rogthoma-dev-01 is reachable
      condition: event is defined
      action:
        run_job_template:
          name: Demo Job Template