---
- name: Hello World Rulebook
  hosts: localhost
  sources:
    - name: periodic
      ansible.eda.time:
        delay: 60  # every 60 seconds
  rules:
    - name: Run Hello World if rogthoma-dev-01 is reachable
      condition: event is defined
      action:
        run_job_template:
          name: Demo Job Template