---
- name: Listen for events on a webhook
  hosts: localhost
  ## Define our source for events
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Run demo template
      condition: event.trigger == "go"
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
